version: '3.8'

services:
  inventory_service:
    build: ./inventory_service
    ports:
      - "5001:5001"
    environment:
      # Set to "1" to enable a 2s artificial delay for testing timeouts
      - INVENTORY_DELAY=1

  notification_service:
    build: ./notification_service
    ports:
      - "5002:5002"

  order_service:
    build: ./order_service
    ports:
      - "5000:5000"
    depends_on:
      - inventory_service
      - notification_service
